CORE-8421 Re-add kameleon dependency, bump to version 3.0.0.
Otherwise an exception is thrown at startup:
java.sql.SQLException: No suitable driver found for jdbc:postgresql…